package Main;
import java.util.ArrayList;

import com.sun.glass.events.KeyEvent;

import Entita.Partita;
import General.GestoreAzioni;
import General.GestoreAzioniEssentials;
import General.GestoreMessaggi;
import General.GestoreMessaggiEssentials;
import Parser.ParserEssentials;
import Parser.ParserIta;
import Parser.ParserOutput;
/**
 *
 * @author RESTA
 */
public class AdventureGUI extends javax.swing.JFrame {

    private GestoreAzioniEssentials azioni;
    private final GestoreMessaggiEssentials stampante = new GestoreMessaggi(this);
    private ParserEssentials parser;

    /**
     * Creates new form AdventureGUI
     */
    public AdventureGUI() {
        initComponents();
        init();
    }

    private void init(){
        Partita partita = new Partita();
        azioni = new GestoreAzioni(partita, stampante);
        azioni.setListaOggetti(partita.getOggetti());
        ArrayList<String> prepositions = new ArrayList<>();
        prepositions.add("in");
        prepositions.add("da");
        prepositions.add("con");
        prepositions.add("dal");
        prepositions.add("dalla");
        prepositions.add("nel");
        prepositions.add("e");
        prepositions.add("all");
        prepositions.add("a");
        prepositions.add("ad");
        ArrayList<String> articles = new ArrayList<>();
        articles.add("la");
        articles.add("l");
        articles.add("il");
        articles.add("un");
        articles.add("una");
        parser = new ParserIta(articles, prepositions);
    }

    public void stampaMessaggio(String messaggio){
        jtConsole.append(messaggio + "\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsole = new javax.swing.JTextArea();
        jlConsole = new javax.swing.JLabel();
        jbOvest = new javax.swing.JButton();
        jbNord = new javax.swing.JButton();
        jbSud = new javax.swing.JButton();
        jbEst = new javax.swing.JButton();
        jtComandi = new javax.swing.JTextField();
        jlComandi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dino Game");

        jtConsole.setEditable(false);
        jtConsole.setColumns(20);
        jtConsole.setRows(5);
        jtConsole.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setViewportView(jtConsole);

        jlConsole.setText("Console");

        jbOvest.setText("OVEST");
        jbOvest.setPreferredSize(new java.awt.Dimension(70, 20));
        jbOvest.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOvestActionPerformed(evt);
            }
        });

        jbNord.setText("NORD");
        jbNord.setPreferredSize(new java.awt.Dimension(70, 20));
        jbNord.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNordActionPerformed(evt);
            }
        });

        jbSud.setText("SUD");
        jbSud.setPreferredSize(new java.awt.Dimension(70, 20));
        jbSud.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSudActionPerformed(evt);
            }
        });

        jbEst.setText("EST");
        jbEst.setPreferredSize(new java.awt.Dimension(70, 20));
        jbEst.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstActionPerformed(evt);
            }
        });

        jtComandi.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
			public void keyPressed(java.awt.event.KeyEvent evt) {
                jtComandiKeyPressed(evt);
            }
        });

        jlComandi.setText("Comandi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbOvest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jbNord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtComandi)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlComandi, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addComponent(jlConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlConsole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlComandi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbOvest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbEst, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtComandi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbNord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSud, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSudActionPerformed
        azioni.movimentoSud();
    }//GEN-LAST:event_jbSudActionPerformed

    private void jbOvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOvestActionPerformed
        azioni.movimentoOvest();
    }//GEN-LAST:event_jbOvestActionPerformed

    private void jbNordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNordActionPerformed
        azioni.movimentoNord();
    }//GEN-LAST:event_jbNordActionPerformed

    private void jbEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstActionPerformed
        azioni.movimentoEst();
    }//GEN-LAST:event_jbEstActionPerformed

    private void jtComandiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtComandiKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String input = jtComandi.getText();
            jtComandi.setText("");
            ParserOutput azione = parser.parse(input, azioni.getComandi(), azioni.getOggetti(), azioni.getPersonaggi());
            if(azione != null){
                azioni.elaboraAzione(azione);
            } else {
                stampante.messaggioComandoNonRiconosciuto();
            }
        }
    }//GEN-LAST:event_jtComandiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdventureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdventureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdventureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdventureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                new AdventureGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEst;
    private javax.swing.JButton jbNord;
    private javax.swing.JButton jbOvest;
    private javax.swing.JButton jbSud;
    private javax.swing.JLabel jlComandi;
    private javax.swing.JLabel jlConsole;
    private javax.swing.JTextField jtComandi;
    private javax.swing.JTextArea jtConsole;
    // End of variables declaration//GEN-END:variables
}
